/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.digitalfemsa;

import com.digitalfemsa.*;
import com.digitalfemsa.auth.*;
import com.digitalfemsa.model.Error;
import com.digitalfemsa.model.GetTransfersResponse;
import com.digitalfemsa.model.TransferResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransfersApi
 */
public class TransfersApiTest {

    private final TransfersApi api = new TransfersApi();

    /**
     * Get Transfer
     *
     * Get the details of a Transfer
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTransferTest() throws ApiException {
        //String id = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //TransferResponse response = api.getTransfer(id, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Get a list of transfers
     *
     * Get transfers details in the form of a list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTransfersTest() throws ApiException {
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //Integer limit = null;
        //String search = null;
        //String next = null;
        //String previous = null;
        //GetTransfersResponse response = api.getTransfers(acceptLanguage, xChildCompanyId, limit, search, next, previous);
        // TODO: test validations
    }

}
