/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa;

import io.digitalfemsa.*;
import io.digitalfemsa.auth.*;
import io.digitalfemsa.model.ChargeOrderResponse;
import io.digitalfemsa.model.ChargeRequest;
import io.digitalfemsa.model.ChargeResponse;
import io.digitalfemsa.model.ChargeUpdateRequest;
import io.digitalfemsa.model.Error;
import io.digitalfemsa.model.GetChargesResponse;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ChargesApi
 */
public class ChargesApiTest {

    private final ChargesApi api = new ChargesApi();

    /**
     * Get A List of Charges
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getChargesTest() throws ApiException {
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //Integer limit = null;
        //String search = null;
        //String next = null;
        //String previous = null;
        //GetChargesResponse response = api.getCharges(acceptLanguage, xChildCompanyId, limit, search, next, previous);
        // TODO: test validations
    }

    /**
     * Create charge
     *
     * Create charge for an existing orden
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersCreateChargeTest() throws ApiException {
        //String id = null;
        //ChargeRequest chargeRequest = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //ChargeOrderResponse response = api.ordersCreateCharge(id, chargeRequest, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Update a charge
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateChargeTest() throws ApiException {
        //String id = null;
        //ChargeUpdateRequest chargeUpdateRequest = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //ChargeResponse response = api.updateCharge(id, chargeUpdateRequest, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

}
