/*
 * Femsa API
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.digitalfemsa;

import io.digitalfemsa.*;
import io.digitalfemsa.auth.*;
import io.digitalfemsa.model.CustomerShippingContacts;
import io.digitalfemsa.model.CustomerShippingContactsResponse;
import io.digitalfemsa.model.CustomerUpdateShippingContacts;
import io.digitalfemsa.model.Error;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ShippingContactsApi
 */
public class ShippingContactsApiTest {

    private final ShippingContactsApi api = new ShippingContactsApi();

    /**
     * Create a shipping contacts
     *
     * Create a shipping contacts for a customer.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createCustomerShippingContactsTest() throws ApiException {
        //String id = null;
        //CustomerShippingContacts customerShippingContacts = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //CustomerShippingContactsResponse response = api.createCustomerShippingContacts(id, customerShippingContacts, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Delete shipping contacts
     *
     * Delete shipping contact that corresponds to a customer ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteCustomerShippingContactsTest() throws ApiException {
        //String id = null;
        //String shippingContactsId = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //CustomerShippingContactsResponse response = api.deleteCustomerShippingContacts(id, shippingContactsId, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

    /**
     * Update shipping contacts
     *
     * Update shipping contact that corresponds to a customer ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateCustomerShippingContactsTest() throws ApiException {
        //String id = null;
        //String shippingContactsId = null;
        //CustomerUpdateShippingContacts customerUpdateShippingContacts = null;
        //String acceptLanguage = null;
        //String xChildCompanyId = null;
        //CustomerShippingContactsResponse response = api.updateCustomerShippingContacts(id, shippingContactsId, customerUpdateShippingContacts, acceptLanguage, xChildCompanyId);
        // TODO: test validations
    }

}
